config/routes.rb
Rails.application.routes.draw do

  resources :billings
  resources :contact_managers
  resources :categories
  resources :vendors
  devise_for :users
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :clients
  resources :projects
  resources :tasks

  get 'dashboard/index'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/sandbox'
  get 'say/projects'
  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role?("super_admin")
        can :manage, :all
    elsif user.role?("admin")
        can :manage, [Client, Project, Task]
        can [:read, :update], [Vendor]
    elsif user.role?("user")
        can [:create, :read, :update], [Client, Project, Task]
    else
    end
  end

end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/billing.rb
class Billing < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :project_categories
	has_many :projects, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	belongs_to :user

	validates_presence_of :name, :company
	validates_presence_of :website, message: "Contact us if you require a website"
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10

end




=begin
	def list_projects
		Project.where('client_id = ?', id)
	end
=end

app/models/contact_manager.rb
class ContactManager < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	# has_many :join_table
	# has_many :associated_table, through: :join_table

	has_many :project_categories
	has_many :categories, through: :project_categories

	belongs_to :client	

	has_many :tasks, dependent: :destroy

	validates_presence_of :name, :description
	validates :status, presence: true

	validates_length_of :description, maximum: 100

end



=begin
	def details
		"#{name} - #{status} - #{start_date} - #{Client.find(client_id).name}"
	end


	def self.list_new_projects
		Project.where('status = ?', 'new')
	end

	def list_tasks
		Task.where('project_id = ?', id)
	end
=end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
	validates_presence_of :project_id
	validates_numericality_of :project_id
	#validate :check_due_date


	private 

	def check_due_date
		if !(due_date).nil? && due_date < project.start_date
			errors.add(:due_date, " of task should be greater than #{project.start_date}")
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions


	def role?(role)
		self.roles.pluck(:name).include?(role)
		#self.roles.map(&:name).include?(role)
	end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	def to_param
		"#{company}"
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	#layout 'clients'
	load_and_authorize_resource
	before_filter :authenticate_user!

	def index
		if params[:status].nil?
			@projects = current_user.projects.paginate(page: params[:page], per_page: 5)
		elsif params[:status] == "new"
			@projects = current_user.projects.where('status = ?', params[:status])
		elsif params[:status] == "completed"
			@projects = current_user.projects.where('status = ?', "completed")
		else 
			@projects = []
		end
	end

	def new
		@project = Project.new
		render layout: 'application'
	end

	def show
		begin
			@project = Project.find(params[:id])
			@task = Task.new
		rescue ActiveRecord::RecordNotFound
			redirect_to projects_path, notice: "Project does not exist"
		end
	end

end

app/controllers/say_controller.rb
class SayController < ApplicationController

  load_and_authorize_resource
  def hello
  end

  def goodbye
  	
  end

  def sandbox
		@clients = Client.all
		@projects = Project.all
		@tasks = Task.all
  end

  def projects
  	@projects = Project.all
  end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/projects/index.html.erb
<div class="col-md-8">
<h3>Listing Projects</h3>
<p><%= link_to "Export to excel", projects_path(format: "xls") %>
<p>Total Projects : <%= @projects.size %></p>
filter by: 
<%= link_to "New", projects_path(status: "new") %> | 
<%= link_to "Completed", projects_path(status: "completed") %> | 
<%= link_to "All", projects_path %>


<% data = {} %>
<% data[:new] = @projects.where('status = ?', "new").count %>
<% data[:completed] = @projects.where('status = ?', "completed").count %>
<% data[:on_going] = @projects.where('status = ?', "on-going").count %>
<% data[:archieved] = @projects.where('status = ?', "archieved").count %>

<%= pie_chart(data) %>

<table class="table table-stripped">
<thead>
	<tr>
		<th>Name</th>
		<th>Status</th>
		<th>Client</th>
	</tr>
</thead>
<tbody>
	<% @projects.each do |project| %>
	<tr>
		<%# link_to project.name, "/projects/#{project.id}" %>
		<td><%= link_to project.name, project_path(project) %></td>
		<td><%= project.status %></td>
		<td><%# project.client.nil? ? "N/A" : project.client.name %>
				<%= project.client.try(:name) %>
		</td>
	</tr>
	<% end %>
</tbody>
</table>

<%= will_paginate %>

<%= link_to "Add Project", new_project_path %>


</div>
<div class="col-md-4">
<h3>Project Stat</h3>
</div>

app/views/projects/index.xls.erb
<h1>Project Details</h1>

<table border="1">
<thead>
	<tr>
		<th>Name</th>
		<th>Status</th>
		<th>Client</th>
		<th>Total Tasks</th>
	</tr>
</thead>
<tbody>
	<% @projects.each do |project| %>
	<tr>
		<%# link_to project.name, "/projects/#{project.id}" %>
		<td><%= link_to project.name, project_url(project) %></td>
		<td><%= project.status %></td>
		<td><%# project.client.nil? ? "N/A" : project.client.name %>
				<%= project.client.try(:name) %>
		</td>
		<td><%= project.tasks.size %></td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/projects/new.html.erb
  <script>
  $(function() {
    $("#datepicker").datepicker();
  });
  </script>

<fieldset>
	<legend><h3>Add Project</h3></legend>
<%= form_for @project do |f| %>

<label>Client </label><br/>
<%= f.collection_select :client_id, Client.all, :id, :company, prompt: "Select Client" %><br/>

<label>Name </label><br/>
<%= f.text_field :name %><br/>

<label>Description </label><br/>
<%= f.text_area :description, rows: 5, cols: 25 %><br/>

<label>Start Date</label><br/>
<%# f.date_select :start_date, order:[:day, :month, :year], start_year: 2015, end_year: (Date.today.year + 3), include_blank: true %><br/>
<%= f.text_field :start_date, id: "datepicker" %>

<label>Status</label><br/>
<%# f.select :status, %w[new on-going completed archieved], prompt: "Select Status" %><br/>

<label>Status</label><br/>
<%= f.radio_button :status, "new" %>New <br/>
<%= f.radio_button :status, "on-going" %>On-Going <br/>
<%= f.radio_button :status, "completed" %>Completed <br/>

<%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>
</fieldset>

app/views/projects/show.html.erb
<h3><%= @project.name %></h3>
<p><%= @project.client.name %> <%= link_to @project.client.website, "#{@project.client.website}", target: "_blank" %>
<hr/>

<h3>Total Tasks - <%= @project.tasks.size %></h3>
<% over_due_tasks = @project.tasks.where('is_completed = ? AND due_date < ?', false, Date.today) %>
<% upcomping_tasks = @project.tasks.where('is_completed = ? AND due_date >= ? AND due_date <= ?', false, Date.today, Date.today + 3.days) %>
<% incomplete_tasks = @project.tasks.where('is_completed = ? AND due_date > ?', false, Date.today + 3.days) %>
<% completed_tasks = @project.tasks.where('is_completed = ?', true) %>

<% unless over_due_tasks.empty? %>
	<h4>Over Due Tasks - <%= over_due_tasks.size %></h4>
	<ul>
		<% over_due_tasks.each do |task| %>
			<li><%= task.name %> - <%= task.due_date.strftime("%A, %d %B %Y") %> 
			<small><%= link_to "Mark as complete", tasks_mark_as_complete_path(task_id: task) %> </small>
			</li>
		<% end %>
	</ul>
<% end %>

<% unless upcomping_tasks.empty? %>
	<h4>Upcoming Tasks - <%= upcomping_tasks.size %></h4>
	<ul>
		<% upcomping_tasks.each do |task| %>
			<li><%= task.name %> - <%= task.due_date.strftime("%A, %d %B %Y") %> <small><%= link_to "Mark as complete", tasks_mark_as_complete_path(task_id: task) %> </small></li>
		<% end %>
	</ul>
<% end %>

<% unless incomplete_tasks.empty? %>
	<h4>Incomplete Tasks - <%= incomplete_tasks.size %></h4>
	<ul>
		<% incomplete_tasks.each do |task| %>
			<li><%= task.name %> - <%= task.due_date.strftime("%A, %d %B %Y") %> <small><%= link_to "Mark as complete", tasks_mark_as_complete_path(task_id: task) %> </small></li>
		<% end %>
	</ul>
<% end %>

<% unless completed_tasks.empty? %>
	<h4>Completed Tasks - <%= completed_tasks.size %></h4>
	<ul>
		<% completed_tasks.each do |task| %>
			<li><%= task.name %> - <%= task.due_date.strftime("%A, %d %B %Y") %> <small><%= link_to "Mark as incomplete", tasks_mark_as_incomplete_path(task_id: task) %> </small></li>
		<% end %>
	</ul>
<% end %>



<h3>Add Task</h3>
<%= form_for @task do |f| %>

<label>Name</label>
<%= f.text_field :name, required: true %><br/>

<label>Due Date</label>
<%= f.date_select :due_date %><br/>

<label>Is Completed? </label>
<%= f.check_box :is_completed %><br/>

<%= f.hidden_field :project_id, value: @project.id %>

<%= f.submit %>

<% end %>