config/routes.rb
Rails.application.routes.draw do

  resources :billings
  resources :contact_managers
  resources :categories
  resources :vendors
  devise_for :users
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :clients
  resources :projects
  resources :tasks

  get 'dashboard/index'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/sandbox'
  get 'say/projects'
  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role?("super_admin")
        can :manage, :all
    elsif user.role?("admin")
        can :manage, [Client, Project, Task]
        can [:read, :update], [Vendor]
    elsif user.role?("user")
        can [:create, :read, :update], [Client, Project, Task]
    else
    end
  end

end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/billing.rb
class Billing < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :project_categories
	has_many :projects, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	belongs_to :user

	validates_presence_of :name, :company
	validates_presence_of :website, message: "Contact us if you require a website"
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10

end




=begin
	def list_projects
		Project.where('client_id = ?', id)
	end
=end

app/models/contact_manager.rb
class ContactManager < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	# has_many :join_table
	# has_many :associated_table, through: :join_table

	has_many :project_categories
	has_many :categories, through: :project_categories

	belongs_to :client	

	has_many :tasks, dependent: :destroy

	validates_presence_of :name, :description
	validates :status, presence: true

	validates_length_of :description, maximum: 100

end



=begin
	def details
		"#{name} - #{status} - #{start_date} - #{Client.find(client_id).name}"
	end


	def self.list_new_projects
		Project.where('status = ?', 'new')
	end

	def list_tasks
		Task.where('project_id = ?', id)
	end
=end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
	validates_presence_of :project_id
	validates_numericality_of :project_id
	#validate :check_due_date


	private 

	def check_due_date
		if !(due_date).nil? && due_date < project.start_date
			errors.add(:due_date, " of task should be greater than #{project.start_date}")
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions


	def role?(role)
		self.roles.pluck(:name).include?(role)
		#self.roles.map(&:name).include?(role)
	end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	def to_param
		"#{company}"
	end

end

app/controllers/contact_managers_controller.rb
class ContactManagersController < ApplicationController
  before_action :set_contact_manager, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /contact_managers
  # GET /contact_managers.json
  def index
    @contact_managers = ContactManager.all
  end

  # GET /contact_managers/1
  # GET /contact_managers/1.json
  def show
  end

  # GET /contact_managers/new
  def new
    @contact_manager = ContactManager.new
  end

  # GET /contact_managers/1/edit
  def edit
  end

  # POST /contact_managers
  # POST /contact_managers.json
  def create
    @contact_manager = ContactManager.new(contact_manager_params)

    respond_to do |format|
      if @contact_manager.save
        format.html { redirect_to @contact_manager, notice: 'Contact manager was successfully created.' }
        format.json { render :show, status: :created, location: @contact_manager }
      else
        format.html { render :new }
        format.json { render json: @contact_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_managers/1
  # PATCH/PUT /contact_managers/1.json
  def update
    respond_to do |format|
      if @contact_manager.update(contact_manager_params)
        format.html { redirect_to @contact_manager, notice: 'Contact manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_manager }
      else
        format.html { render :edit }
        format.json { render json: @contact_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_managers/1
  # DELETE /contact_managers/1.json
  def destroy
    @contact_manager.destroy
    respond_to do |format|
      format.html { redirect_to contact_managers_url, notice: 'Contact manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_manager
      @contact_manager = ContactManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_manager_params
      params.require(:contact_manager).permit(:first_name, :last_name, :mobile, :email)
    end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contact_managers_helper.rb
module ContactManagersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/contact_managers/_form.html.erb
<%= form_for(@contact_manager) do |f| %>
  <% if @contact_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_manager.errors.count, "error") %> prohibited this contact_manager from being saved:</h2>

      <ul>
      <% @contact_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>First Name:</label><br/>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_managers/edit.html.erb
<h1>Editing Contact Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_manager %> |
<%= link_to 'Back', contact_managers_path %>

app/views/contact_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All My Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_managers.each do |contact_manager| %>
      <tr>
        <td><%= contact_manager.first_name %></td>
        <td><%= contact_manager.last_name %></td>
        <td><%= contact_manager.mobile %></td>
        <td><%= contact_manager.email %></td>
        <td><%= link_to 'Show', contact_manager %></td>
        <td><%= link_to 'Edit', edit_contact_manager_path(contact_manager) %></td>
        <td><%= link_to 'Destroy', contact_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_manager_path %>

app/views/contact_managers/new.html.erb
<h1>New Contact Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_managers_path %>

app/views/contact_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact_manager.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact_manager.last_name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact_manager.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_manager.email %>
</p>

<%= link_to 'Edit', edit_contact_manager_path(@contact_manager) %> |
<%= link_to 'Back', contact_managers_path %>