config/routes.rb
Rails.application.routes.draw do

  resources :billings
  resources :contact_managers
  resources :categories
  resources :vendors
  devise_for :users
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :clients
  resources :projects
  resources :tasks

  get 'dashboard/index'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/sandbox'
  get 'say/projects'
  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role?("super_admin")
        can :manage, :all
    elsif user.role?("admin")
        can :manage, [Client, Project, Task]
        can [:read, :update], [Vendor]
    elsif user.role?("user")
        can [:create, :read, :update], [Client, Project, Task]
    else
    end
  end

end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/billing.rb
class Billing < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :project_categories
	has_many :projects, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	belongs_to :user

	validates_presence_of :name, :company
	validates_presence_of :website, message: "Contact us if you require a website"
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10

end




=begin
	def list_projects
		Project.where('client_id = ?', id)
	end
=end

app/models/contact_manager.rb
class ContactManager < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	# has_many :join_table
	# has_many :associated_table, through: :join_table

	has_many :project_categories
	has_many :categories, through: :project_categories

	belongs_to :client	

	has_many :tasks, dependent: :destroy

	validates_presence_of :name, :description
	validates :status, presence: true

	validates_length_of :description, maximum: 100

end



=begin
	def details
		"#{name} - #{status} - #{start_date} - #{Client.find(client_id).name}"
	end


	def self.list_new_projects
		Project.where('status = ?', 'new')
	end

	def list_tasks
		Task.where('project_id = ?', id)
	end
=end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
	validates_presence_of :project_id
	validates_numericality_of :project_id
	#validate :check_due_date


	private 

	def check_due_date
		if !(due_date).nil? && due_date < project.start_date
			errors.add(:due_date, " of task should be greater than #{project.start_date}")
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions


	def role?(role)
		self.roles.pluck(:name).include?(role)
		#self.roles.map(&:name).include?(role)
	end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	def to_param
		"#{company}"
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			respond_to do |format|
				format.html
				format.js
			end
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update_attributes(category_params)
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
	end

	private

	def category_params
		params[:category].permit(:name)
	end

end

app/controllers/say_controller.rb
class SayController < ApplicationController

  load_and_authorize_resource
  def hello
  end

  def goodbye
  	
  end

  def sandbox
		@clients = Client.all
		@projects = Project.all
		@tasks = Task.all
  end

  def projects
  	@projects = Project.all
  end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, remote: true do |f| %>
	<%= f.text_field :name, placeholder: "Category Name" %>
<% end %>

app/views/categories/create.js.erb
$('#category_count').text('<%= Category.count %>');
$('#category_list').append('<li id="li_<%= @category.id %>"><%= @category.name %> <%= link_to "X", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %> </li>');
$('#new_category').hide();
$('#add_category').show();

app/views/categories/destroy.js.erb
$('#category_count').text('<%= Category.count %>');
$('#li_<%= @category.id %>').slideUp();

app/views/categories/edit.js.erb
$("#add_category").hide().after('<%= j render("form") %>');

app/views/categories/index.html.erb
<h3>Listing Categories - ( <span id="category_count"><%= @categories.size %></span> )</h3>

<ul id="category_list">
	<% for category in @categories %>
		<li id="li_<%= category.id %>">
		<%= category.name %>

		<%= link_to edit_category_path(category), remote: true do %>
			<span class="glyphicon glyphicon-pencil"></span>
		<% end %>


		 <%= link_to "X", category_path(category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
		</li>
	<% end %>
</ul>

<%= link_to "Add Category", new_category_path, id:"add_category", remote: true %>

app/views/categories/new.js.erb
$('#add_category').hide().after('<%= j render("form") %>');

app/views/categories/update.js.erb
$('#li_<%= @category.id %>').html('<%= @category.name %> <%= link_to "X", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %> ');
$('#edit_category_<%= @category.id %>').hide();
$('#add_category').show();